# permissions for end users to view appsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: appset-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: appset
    app.kubernetes.io/part-of: appset
    app.kubernetes.io/managed-by: kustomize
  name: appset-viewer-role
rules:
- apiGroups:
  - apps.hh.org
  resources:
  - appsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.hh.org
  resources:
  - appsets/status
  verbs:
  - get
