apiVersion: apps.hh.org/v1
kind: AppSet
metadata:
  labels:
    app.kubernetes.io/name: appset
    app.kubernetes.io/instance: appset-sample
    app.kubernetes.io/part-of: appset
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: appset
  name: appset-sample
  namespace: default
spec:
  # TODO(user): Add fields here
  replicas: 3
  # latest | stable-perl
  image: "nginx:stable-perl"
  expose_port: 80
  expose_domain: www.monkey.org
